name: Build to DockerHub

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the flask-app repo
        uses: actions/checkout@v2
        
      - name: Autheticate to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        
      - name: build flask-app and push to dockerhub
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          context: ./
          file: ./Whist-EXC/Whist-Exam/docker-compose.yml
          push: true
          tags: yarden/flask-app:latest
